# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies and build the project
RUN npm install --ignore-scripts && npm run build

# Use a separate image for the runtime
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json

# Install only production dependencies
RUN npm ci --omit=dev

# Command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]
